# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'

- bash: |
   pip install pytest 
   pip install pytest-xdist
   pip install flaky
  displayName: 'Install a bunch of pip packages.'

- bash: 'pytest --junitxml=$(Build.StagingDirectory)/report.xml' 
  workingDirectory: 'test_suit'
  displayName: 'Run tests'

- task: PublishTestResults@2
  displayName: 'Publish test result /report.xml'
  inputs:
    testResultsFiles: '$(Build.StagingDirectory)/report.xml'
    testRunTitle: main